CREATE TYPE category AS ENUM (
  'Substance Use',
  'Disability Services',
  'Sexual & Domestic Violence',
  'Mental Health'
  'Animal Services',
  'Residence Challenged',
  'LGBTQ+',
  'Immigration Services',
  'Veterans'
);

CREATE TABLE resources (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    phone_number CHAR(10) NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT NOT NULL,
    zip_code CHAR(5),
    county TEXT NOT NULL,
    url TEXT,
    facebook TEXT,
    twitter TEXT,
    instagram TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
