CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    nickname TEXT,
    title_id INTEGER
        REFERENCES resources(id) ON DELETE CASCADE,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);


ALTER TABLE resources 
  ADD COLUMN
    user_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL;
