CREATE TABLE resource (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER REFERENCES category(id),
    title TEXT NOT NULL,
    phone_number CHAR(10) NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT NOT NULL,
    zip_code CHAR(5),
    county TEXT NOT NULL,
    url TEXT,
    facebook TEXT,
    twitter TEXT,
    instagram TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE category
    ADD COLUMN
        resource_id INTEGER REFERENCES resource(id)
        ON DELETE SET NULL;